// Code generated by pigeon; DO NOT EDIT.

// https://github.com/mna/pigeon

package lep

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"
)

var g = &grammar{
	rules: []*rule{
		{
			name: "Input",
			pos:  position{line: 7, col: 1, offset: 51},
			expr: &actionExpr{
				pos: position{line: 7, col: 10, offset: 60},
				run: (*parser).callonInput1,
				expr: &seqExpr{
					pos: position{line: 7, col: 10, offset: 60},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 7, col: 10, offset: 60},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 7, col: 15, offset: 65},
								name: "Expr",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 7, col: 20, offset: 70},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "Expr",
			pos:  position{line: 8, col: 1, offset: 95},
			expr: &choiceExpr{
				pos: position{line: 8, col: 10, offset: 104},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 8, col: 10, offset: 104},
						name: "Or",
					},
					&ruleRefExpr{
						pos:  position{line: 8, col: 15, offset: 109},
						name: "And",
					},
					&ruleRefExpr{
						pos:  position{line: 8, col: 21, offset: 115},
						name: "Bracket",
					},
					&ruleRefExpr{
						pos:  position{line: 8, col: 31, offset: 125},
						name: "Statements",
					},
				},
			},
		},
		{
			name: "Statements",
			pos:  position{line: 9, col: 1, offset: 137},
			expr: &choiceExpr{
				pos: position{line: 9, col: 16, offset: 152},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 9, col: 16, offset: 152},
						name: "Comparators",
					},
					&ruleRefExpr{
						pos:  position{line: 9, col: 30, offset: 166},
						name: "StringOps",
					},
					&ruleRefExpr{
						pos:  position{line: 9, col: 42, offset: 178},
						name: "SliceOps",
					},
					&ruleRefExpr{
						pos:  position{line: 9, col: 53, offset: 189},
						name: "ContainOps",
					},
					&ruleRefExpr{
						pos:  position{line: 9, col: 66, offset: 202},
						name: "RegexpOps",
					},
				},
			},
		},
		{
			name: "Bracket",
			pos:  position{line: 10, col: 1, offset: 213},
			expr: &actionExpr{
				pos: position{line: 10, col: 12, offset: 224},
				run: (*parser).callonBracket1,
				expr: &seqExpr{
					pos: position{line: 10, col: 12, offset: 224},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 10, col: 12, offset: 224},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 10, col: 14, offset: 226},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&ruleRefExpr{
							pos:  position{line: 10, col: 18, offset: 230},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 10, col: 20, offset: 232},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 10, col: 25, offset: 237},
								name: "Expr",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 10, col: 30, offset: 242},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 10, col: 32, offset: 244},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
						&ruleRefExpr{
							pos:  position{line: 10, col: 36, offset: 248},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "Param",
			pos:  position{line: 11, col: 1, offset: 271},
			expr: &actionExpr{
				pos: position{line: 11, col: 10, offset: 280},
				run: (*parser).callonParam1,
				expr: &seqExpr{
					pos: position{line: 11, col: 10, offset: 280},
					exprs: []interface{}{
						&charClassMatcher{
							pos:        position{line: 11, col: 10, offset: 280},
							val:        "[a-zA-Z]",
							ranges:     []rune{'a', 'z', 'A', 'Z'},
							ignoreCase: false,
							inverted:   false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 11, col: 19, offset: 289},
							expr: &charClassMatcher{
								pos:        position{line: 11, col: 19, offset: 289},
								val:        "[a-zA-Z0-9_.]",
								chars:      []rune{'_', '.'},
								ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "Values",
			pos:  position{line: 14, col: 1, offset: 345},
			expr: &choiceExpr{
				pos: position{line: 14, col: 12, offset: 356},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 14, col: 12, offset: 356},
						name: "Null",
					},
					&ruleRefExpr{
						pos:  position{line: 14, col: 19, offset: 363},
						name: "Boolean",
					},
					&ruleRefExpr{
						pos:  position{line: 14, col: 29, offset: 373},
						name: "Float",
					},
					&ruleRefExpr{
						pos:  position{line: 14, col: 37, offset: 381},
						name: "Integer",
					},
					&ruleRefExpr{
						pos:  position{line: 14, col: 47, offset: 391},
						name: "DateTime",
					},
					&ruleRefExpr{
						pos:  position{line: 14, col: 58, offset: 402},
						name: "String",
					},
				},
			},
		},
		{
			name: "Null",
			pos:  position{line: 15, col: 1, offset: 410},
			expr: &actionExpr{
				pos: position{line: 15, col: 9, offset: 418},
				run: (*parser).callonNull1,
				expr: &litMatcher{
					pos:        position{line: 15, col: 9, offset: 418},
					val:        "null",
					ignoreCase: false,
					want:       "\"null\"",
				},
			},
		},
		{
			name: "Boolean",
			pos:  position{line: 16, col: 1, offset: 448},
			expr: &actionExpr{
				pos: position{line: 16, col: 12, offset: 459},
				run: (*parser).callonBoolean1,
				expr: &choiceExpr{
					pos: position{line: 16, col: 13, offset: 460},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 16, col: 13, offset: 460},
							val:        "true",
							ignoreCase: false,
							want:       "\"true\"",
						},
						&litMatcher{
							pos:        position{line: 16, col: 22, offset: 469},
							val:        "false",
							ignoreCase: false,
							want:       "\"false\"",
						},
					},
				},
			},
		},
		{
			name: "Float",
			pos:  position{line: 17, col: 1, offset: 510},
			expr: &actionExpr{
				pos: position{line: 17, col: 10, offset: 519},
				run: (*parser).callonFloat1,
				expr: &seqExpr{
					pos: position{line: 17, col: 10, offset: 519},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 17, col: 10, offset: 519},
							expr: &litMatcher{
								pos:        position{line: 17, col: 10, offset: 519},
								val:        "-",
								ignoreCase: false,
								want:       "\"-\"",
							},
						},
						&oneOrMoreExpr{
							pos: position{line: 17, col: 15, offset: 524},
							expr: &charClassMatcher{
								pos:        position{line: 17, col: 15, offset: 524},
								val:        "[0-9]",
								ranges:     []rune{'0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
						&charClassMatcher{
							pos:        position{line: 17, col: 21, offset: 530},
							val:        "[.]",
							chars:      []rune{'.'},
							ignoreCase: false,
							inverted:   false,
						},
						&oneOrMoreExpr{
							pos: position{line: 17, col: 24, offset: 533},
							expr: &charClassMatcher{
								pos:        position{line: 17, col: 24, offset: 533},
								val:        "[0-9]",
								ranges:     []rune{'0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "Integer",
			pos:  position{line: 18, col: 1, offset: 570},
			expr: &actionExpr{
				pos: position{line: 18, col: 12, offset: 581},
				run: (*parser).callonInteger1,
				expr: &seqExpr{
					pos: position{line: 18, col: 12, offset: 581},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 18, col: 12, offset: 581},
							expr: &litMatcher{
								pos:        position{line: 18, col: 12, offset: 581},
								val:        "-",
								ignoreCase: false,
								want:       "\"-\"",
							},
						},
						&oneOrMoreExpr{
							pos: position{line: 18, col: 17, offset: 586},
							expr: &charClassMatcher{
								pos:        position{line: 18, col: 17, offset: 586},
								val:        "[0-9]",
								ranges:     []rune{'0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "String",
			pos:  position{line: 19, col: 1, offset: 625},
			expr: &actionExpr{
				pos: position{line: 19, col: 11, offset: 635},
				run: (*parser).callonString1,
				expr: &seqExpr{
					pos: position{line: 19, col: 11, offset: 635},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 19, col: 11, offset: 635},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
						&zeroOrMoreExpr{
							pos: position{line: 19, col: 15, offset: 639},
							expr: &charClassMatcher{
								pos:        position{line: 19, col: 15, offset: 639},
								val:        "[^\"]",
								chars:      []rune{'"'},
								ignoreCase: false,
								inverted:   true,
							},
						},
						&litMatcher{
							pos:        position{line: 19, col: 21, offset: 645},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
					},
				},
			},
		},
		{
			name: "DateTime",
			pos:  position{line: 20, col: 1, offset: 680},
			expr: &actionExpr{
				pos: position{line: 20, col: 13, offset: 692},
				run: (*parser).callonDateTime1,
				expr: &seqExpr{
					pos: position{line: 20, col: 13, offset: 692},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 20, col: 13, offset: 692},
							val:        "dt:",
							ignoreCase: false,
							want:       "\"dt:\"",
						},
						&labeledExpr{
							pos:   position{line: 20, col: 19, offset: 698},
							label: "val",
							expr: &ruleRefExpr{
								pos:  position{line: 20, col: 24, offset: 703},
								name: "String",
							},
						},
					},
				},
			},
		},
		{
			name: "Comparators",
			pos:  position{line: 23, col: 1, offset: 757},
			expr: &choiceExpr{
				pos: position{line: 23, col: 17, offset: 773},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 23, col: 17, offset: 773},
						name: "NotEqual",
					},
					&ruleRefExpr{
						pos:  position{line: 23, col: 28, offset: 784},
						name: "Equal",
					},
					&ruleRefExpr{
						pos:  position{line: 23, col: 36, offset: 792},
						name: "GreaterThanEqual",
					},
					&ruleRefExpr{
						pos:  position{line: 23, col: 55, offset: 811},
						name: "GreaterThan",
					},
					&ruleRefExpr{
						pos:  position{line: 23, col: 69, offset: 825},
						name: "LessThanEqual",
					},
					&ruleRefExpr{
						pos:  position{line: 23, col: 85, offset: 841},
						name: "LessThan",
					},
					&ruleRefExpr{
						pos:  position{line: 23, col: 96, offset: 852},
						name: "Between",
					},
				},
			},
		},
		{
			name: "Equal",
			pos:  position{line: 24, col: 1, offset: 861},
			expr: &actionExpr{
				pos: position{line: 24, col: 10, offset: 870},
				run: (*parser).callonEqual1,
				expr: &seqExpr{
					pos: position{line: 24, col: 10, offset: 870},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 24, col: 10, offset: 870},
							label: "left",
							expr: &ruleRefExpr{
								pos:  position{line: 24, col: 16, offset: 876},
								name: "Param",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 24, col: 23, offset: 883},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 24, col: 25, offset: 885},
							val:        "=",
							ignoreCase: false,
							want:       "\"=\"",
						},
						&ruleRefExpr{
							pos:  position{line: 24, col: 29, offset: 889},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 24, col: 31, offset: 891},
							label: "right",
							expr: &choiceExpr{
								pos: position{line: 24, col: 38, offset: 898},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 24, col: 38, offset: 898},
										name: "Values",
									},
									&ruleRefExpr{
										pos:  position{line: 24, col: 47, offset: 907},
										name: "Param",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "NotEqual",
			pos:  position{line: 25, col: 1, offset: 950},
			expr: &actionExpr{
				pos: position{line: 25, col: 13, offset: 962},
				run: (*parser).callonNotEqual1,
				expr: &seqExpr{
					pos: position{line: 25, col: 13, offset: 962},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 25, col: 13, offset: 962},
							label: "left",
							expr: &ruleRefExpr{
								pos:  position{line: 25, col: 19, offset: 968},
								name: "Param",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 25, col: 26, offset: 975},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 25, col: 28, offset: 977},
							val:        "!=",
							ignoreCase: false,
							want:       "\"!=\"",
						},
						&ruleRefExpr{
							pos:  position{line: 25, col: 33, offset: 982},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 25, col: 35, offset: 984},
							label: "right",
							expr: &choiceExpr{
								pos: position{line: 25, col: 42, offset: 991},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 25, col: 42, offset: 991},
										name: "Values",
									},
									&ruleRefExpr{
										pos:  position{line: 25, col: 51, offset: 1000},
										name: "Param",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "LessThan",
			pos:  position{line: 26, col: 1, offset: 1046},
			expr: &actionExpr{
				pos: position{line: 26, col: 13, offset: 1058},
				run: (*parser).callonLessThan1,
				expr: &seqExpr{
					pos: position{line: 26, col: 13, offset: 1058},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 26, col: 13, offset: 1058},
							label: "left",
							expr: &ruleRefExpr{
								pos:  position{line: 26, col: 19, offset: 1064},
								name: "Param",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 26, col: 26, offset: 1071},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 26, col: 28, offset: 1073},
							val:        "<",
							ignoreCase: false,
							want:       "\"<\"",
						},
						&ruleRefExpr{
							pos:  position{line: 26, col: 32, offset: 1077},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 26, col: 34, offset: 1079},
							label: "right",
							expr: &choiceExpr{
								pos: position{line: 26, col: 41, offset: 1086},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 26, col: 41, offset: 1086},
										name: "Values",
									},
									&ruleRefExpr{
										pos:  position{line: 26, col: 50, offset: 1095},
										name: "Param",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "LessThanEqual",
			pos:  position{line: 27, col: 1, offset: 1140},
			expr: &actionExpr{
				pos: position{line: 27, col: 18, offset: 1157},
				run: (*parser).callonLessThanEqual1,
				expr: &seqExpr{
					pos: position{line: 27, col: 18, offset: 1157},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 27, col: 18, offset: 1157},
							label: "left",
							expr: &ruleRefExpr{
								pos:  position{line: 27, col: 24, offset: 1163},
								name: "Param",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 27, col: 31, offset: 1170},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 27, col: 33, offset: 1172},
							val:        "<=",
							ignoreCase: false,
							want:       "\"<=\"",
						},
						&ruleRefExpr{
							pos:  position{line: 27, col: 38, offset: 1177},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 27, col: 40, offset: 1179},
							label: "right",
							expr: &choiceExpr{
								pos: position{line: 27, col: 47, offset: 1186},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 27, col: 47, offset: 1186},
										name: "Values",
									},
									&ruleRefExpr{
										pos:  position{line: 27, col: 56, offset: 1195},
										name: "Param",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "GreaterThan",
			pos:  position{line: 28, col: 1, offset: 1245},
			expr: &actionExpr{
				pos: position{line: 28, col: 16, offset: 1260},
				run: (*parser).callonGreaterThan1,
				expr: &seqExpr{
					pos: position{line: 28, col: 16, offset: 1260},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 28, col: 16, offset: 1260},
							label: "left",
							expr: &ruleRefExpr{
								pos:  position{line: 28, col: 22, offset: 1266},
								name: "Param",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 28, col: 29, offset: 1273},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 28, col: 31, offset: 1275},
							val:        ">",
							ignoreCase: false,
							want:       "\">\"",
						},
						&ruleRefExpr{
							pos:  position{line: 28, col: 35, offset: 1279},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 28, col: 37, offset: 1281},
							label: "right",
							expr: &choiceExpr{
								pos: position{line: 28, col: 44, offset: 1288},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 28, col: 44, offset: 1288},
										name: "Values",
									},
									&ruleRefExpr{
										pos:  position{line: 28, col: 53, offset: 1297},
										name: "Param",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "GreaterThanEqual",
			pos:  position{line: 29, col: 1, offset: 1345},
			expr: &actionExpr{
				pos: position{line: 29, col: 21, offset: 1365},
				run: (*parser).callonGreaterThanEqual1,
				expr: &seqExpr{
					pos: position{line: 29, col: 21, offset: 1365},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 29, col: 21, offset: 1365},
							label: "left",
							expr: &ruleRefExpr{
								pos:  position{line: 29, col: 27, offset: 1371},
								name: "Param",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 29, col: 34, offset: 1378},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 29, col: 36, offset: 1380},
							val:        ">=",
							ignoreCase: false,
							want:       "\">=\"",
						},
						&ruleRefExpr{
							pos:  position{line: 29, col: 41, offset: 1385},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 29, col: 43, offset: 1387},
							label: "right",
							expr: &choiceExpr{
								pos: position{line: 29, col: 50, offset: 1394},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 29, col: 50, offset: 1394},
										name: "Values",
									},
									&ruleRefExpr{
										pos:  position{line: 29, col: 59, offset: 1403},
										name: "Param",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Between",
			pos:  position{line: 30, col: 1, offset: 1456},
			expr: &actionExpr{
				pos: position{line: 30, col: 12, offset: 1467},
				run: (*parser).callonBetween1,
				expr: &seqExpr{
					pos: position{line: 30, col: 12, offset: 1467},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 30, col: 12, offset: 1467},
							label: "left",
							expr: &ruleRefExpr{
								pos:  position{line: 30, col: 18, offset: 1473},
								name: "Param",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 30, col: 25, offset: 1480},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 30, col: 27, offset: 1482},
							val:        "between",
							ignoreCase: false,
							want:       "\"between\"",
						},
						&ruleRefExpr{
							pos:  position{line: 30, col: 37, offset: 1492},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 30, col: 39, offset: 1494},
							label: "start",
							expr: &choiceExpr{
								pos: position{line: 30, col: 46, offset: 1501},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 30, col: 46, offset: 1501},
										name: "Values",
									},
									&ruleRefExpr{
										pos:  position{line: 30, col: 55, offset: 1510},
										name: "Param",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 30, col: 62, offset: 1517},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 30, col: 64, offset: 1519},
							val:        "and",
							ignoreCase: false,
							want:       "\"and\"",
						},
						&ruleRefExpr{
							pos:  position{line: 30, col: 70, offset: 1525},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 30, col: 72, offset: 1527},
							label: "end",
							expr: &choiceExpr{
								pos: position{line: 30, col: 77, offset: 1532},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 30, col: 77, offset: 1532},
										name: "Values",
									},
									&ruleRefExpr{
										pos:  position{line: 30, col: 86, offset: 1541},
										name: "Param",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "StringOps",
			pos:  position{line: 32, col: 1, offset: 1600},
			expr: &choiceExpr{
				pos: position{line: 32, col: 15, offset: 1614},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 32, col: 15, offset: 1614},
						name: "StartsWith",
					},
					&ruleRefExpr{
						pos:  position{line: 32, col: 28, offset: 1627},
						name: "EndsWith",
					},
				},
			},
		},
		{
			name: "StartsWith",
			pos:  position{line: 33, col: 1, offset: 1637},
			expr: &actionExpr{
				pos: position{line: 33, col: 15, offset: 1651},
				run: (*parser).callonStartsWith1,
				expr: &seqExpr{
					pos: position{line: 33, col: 15, offset: 1651},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 33, col: 15, offset: 1651},
							label: "left",
							expr: &ruleRefExpr{
								pos:  position{line: 33, col: 21, offset: 1657},
								name: "Param",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 33, col: 28, offset: 1664},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 33, col: 30, offset: 1666},
							val:        "starts_with",
							ignoreCase: false,
							want:       "\"starts_with\"",
						},
						&ruleRefExpr{
							pos:  position{line: 33, col: 44, offset: 1680},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 33, col: 46, offset: 1682},
							label: "right",
							expr: &choiceExpr{
								pos: position{line: 33, col: 53, offset: 1689},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 33, col: 53, offset: 1689},
										name: "String",
									},
									&ruleRefExpr{
										pos:  position{line: 33, col: 62, offset: 1698},
										name: "Param",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "EndsWith",
			pos:  position{line: 34, col: 1, offset: 1745},
			expr: &actionExpr{
				pos: position{line: 34, col: 13, offset: 1757},
				run: (*parser).callonEndsWith1,
				expr: &seqExpr{
					pos: position{line: 34, col: 13, offset: 1757},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 34, col: 13, offset: 1757},
							label: "left",
							expr: &ruleRefExpr{
								pos:  position{line: 34, col: 19, offset: 1763},
								name: "Param",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 34, col: 26, offset: 1770},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 34, col: 28, offset: 1772},
							val:        "ends_with",
							ignoreCase: false,
							want:       "\"ends_with\"",
						},
						&ruleRefExpr{
							pos:  position{line: 34, col: 40, offset: 1784},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 34, col: 42, offset: 1786},
							label: "right",
							expr: &choiceExpr{
								pos: position{line: 34, col: 49, offset: 1793},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 34, col: 49, offset: 1793},
										name: "String",
									},
									&ruleRefExpr{
										pos:  position{line: 34, col: 58, offset: 1802},
										name: "Param",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "SliceOps",
			pos:  position{line: 37, col: 1, offset: 1858},
			expr: &choiceExpr{
				pos: position{line: 37, col: 14, offset: 1871},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 37, col: 14, offset: 1871},
						name: "InSlice",
					},
					&ruleRefExpr{
						pos:  position{line: 37, col: 24, offset: 1881},
						name: "NotInSlice",
					},
				},
			},
		},
		{
			name: "Slice",
			pos:  position{line: 38, col: 1, offset: 1893},
			expr: &actionExpr{
				pos: position{line: 38, col: 10, offset: 1902},
				run: (*parser).callonSlice1,
				expr: &seqExpr{
					pos: position{line: 38, col: 10, offset: 1902},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 38, col: 10, offset: 1902},
							val:        "[",
							ignoreCase: false,
							want:       "\"[\"",
						},
						&labeledExpr{
							pos:   position{line: 38, col: 14, offset: 1906},
							label: "elements",
							expr: &oneOrMoreExpr{
								pos: position{line: 38, col: 23, offset: 1915},
								expr: &choiceExpr{
									pos: position{line: 38, col: 24, offset: 1916},
									alternatives: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 38, col: 24, offset: 1916},
											name: "Values",
										},
										&litMatcher{
											pos:        position{line: 38, col: 33, offset: 1925},
											val:        ",",
											ignoreCase: false,
											want:       "\",\"",
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 38, col: 39, offset: 1931},
							val:        "]",
							ignoreCase: false,
							want:       "\"]\"",
						},
					},
				},
			},
		},
		{
			name: "InSlice",
			pos:  position{line: 39, col: 1, offset: 1967},
			expr: &actionExpr{
				pos: position{line: 39, col: 12, offset: 1978},
				run: (*parser).callonInSlice1,
				expr: &seqExpr{
					pos: position{line: 39, col: 12, offset: 1978},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 39, col: 12, offset: 1978},
							label: "left",
							expr: &ruleRefExpr{
								pos:  position{line: 39, col: 18, offset: 1984},
								name: "Param",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 39, col: 25, offset: 1991},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 39, col: 27, offset: 1993},
							val:        "in",
							ignoreCase: false,
							want:       "\"in\"",
						},
						&ruleRefExpr{
							pos:  position{line: 39, col: 32, offset: 1998},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 39, col: 34, offset: 2000},
							label: "right",
							expr: &ruleRefExpr{
								pos:  position{line: 39, col: 41, offset: 2007},
								name: "Slice",
							},
						},
					},
				},
			},
		},
		{
			name: "NotInSlice",
			pos:  position{line: 40, col: 1, offset: 2051},
			expr: &actionExpr{
				pos: position{line: 40, col: 15, offset: 2065},
				run: (*parser).callonNotInSlice1,
				expr: &seqExpr{
					pos: position{line: 40, col: 15, offset: 2065},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 40, col: 15, offset: 2065},
							label: "left",
							expr: &ruleRefExpr{
								pos:  position{line: 40, col: 21, offset: 2071},
								name: "Param",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 40, col: 28, offset: 2078},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 40, col: 30, offset: 2080},
							val:        "not_in",
							ignoreCase: false,
							want:       "\"not_in\"",
						},
						&ruleRefExpr{
							pos:  position{line: 40, col: 39, offset: 2089},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 40, col: 41, offset: 2091},
							label: "right",
							expr: &ruleRefExpr{
								pos:  position{line: 40, col: 48, offset: 2098},
								name: "Slice",
							},
						},
					},
				},
			},
		},
		{
			name: "ContainOps",
			pos:  position{line: 43, col: 1, offset: 2158},
			expr: &choiceExpr{
				pos: position{line: 43, col: 16, offset: 2173},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 43, col: 16, offset: 2173},
						name: "Has",
					},
					&ruleRefExpr{
						pos:  position{line: 43, col: 22, offset: 2179},
						name: "NotHas",
					},
					&ruleRefExpr{
						pos:  position{line: 43, col: 31, offset: 2188},
						name: "HasAny",
					},
					&ruleRefExpr{
						pos:  position{line: 43, col: 40, offset: 2197},
						name: "HasAll",
					},
				},
			},
		},
		{
			name: "Has",
			pos:  position{line: 44, col: 1, offset: 2205},
			expr: &actionExpr{
				pos: position{line: 44, col: 8, offset: 2212},
				run: (*parser).callonHas1,
				expr: &seqExpr{
					pos: position{line: 44, col: 8, offset: 2212},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 44, col: 8, offset: 2212},
							label: "left",
							expr: &ruleRefExpr{
								pos:  position{line: 44, col: 14, offset: 2218},
								name: "Param",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 44, col: 21, offset: 2225},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 44, col: 23, offset: 2227},
							val:        "has",
							ignoreCase: false,
							want:       "\"has\"",
						},
						&ruleRefExpr{
							pos:  position{line: 44, col: 29, offset: 2233},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 44, col: 31, offset: 2235},
							label: "right",
							expr: &ruleRefExpr{
								pos:  position{line: 44, col: 38, offset: 2242},
								name: "Values",
							},
						},
					},
				},
			},
		},
		{
			name: "NotHas",
			pos:  position{line: 45, col: 1, offset: 2283},
			expr: &actionExpr{
				pos: position{line: 45, col: 11, offset: 2293},
				run: (*parser).callonNotHas1,
				expr: &seqExpr{
					pos: position{line: 45, col: 11, offset: 2293},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 45, col: 11, offset: 2293},
							label: "left",
							expr: &ruleRefExpr{
								pos:  position{line: 45, col: 17, offset: 2299},
								name: "Param",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 45, col: 24, offset: 2306},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 45, col: 26, offset: 2308},
							val:        "not_has",
							ignoreCase: false,
							want:       "\"not_has\"",
						},
						&ruleRefExpr{
							pos:  position{line: 45, col: 36, offset: 2318},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 45, col: 38, offset: 2320},
							label: "right",
							expr: &ruleRefExpr{
								pos:  position{line: 45, col: 45, offset: 2327},
								name: "Values",
							},
						},
					},
				},
			},
		},
		{
			name: "HasAny",
			pos:  position{line: 46, col: 1, offset: 2371},
			expr: &actionExpr{
				pos: position{line: 46, col: 11, offset: 2381},
				run: (*parser).callonHasAny1,
				expr: &seqExpr{
					pos: position{line: 46, col: 11, offset: 2381},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 46, col: 11, offset: 2381},
							label: "left",
							expr: &ruleRefExpr{
								pos:  position{line: 46, col: 17, offset: 2387},
								name: "Param",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 46, col: 24, offset: 2394},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 46, col: 26, offset: 2396},
							val:        "has_any",
							ignoreCase: false,
							want:       "\"has_any\"",
						},
						&ruleRefExpr{
							pos:  position{line: 46, col: 36, offset: 2406},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 46, col: 38, offset: 2408},
							label: "right",
							expr: &ruleRefExpr{
								pos:  position{line: 46, col: 45, offset: 2415},
								name: "Slice",
							},
						},
					},
				},
			},
		},
		{
			name: "HasAll",
			pos:  position{line: 47, col: 1, offset: 2458},
			expr: &actionExpr{
				pos: position{line: 47, col: 11, offset: 2468},
				run: (*parser).callonHasAll1,
				expr: &seqExpr{
					pos: position{line: 47, col: 11, offset: 2468},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 47, col: 11, offset: 2468},
							label: "left",
							expr: &ruleRefExpr{
								pos:  position{line: 47, col: 17, offset: 2474},
								name: "Param",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 47, col: 24, offset: 2481},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 47, col: 26, offset: 2483},
							val:        "has_all",
							ignoreCase: false,
							want:       "\"has_all\"",
						},
						&ruleRefExpr{
							pos:  position{line: 47, col: 36, offset: 2493},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 47, col: 38, offset: 2495},
							label: "right",
							expr: &ruleRefExpr{
								pos:  position{line: 47, col: 45, offset: 2502},
								name: "Slice",
							},
						},
					},
				},
			},
		},
		{
			name: "RegexpOps",
			pos:  position{line: 50, col: 1, offset: 2568},
			expr: &choiceExpr{
				pos: position{line: 50, col: 15, offset: 2582},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 50, col: 15, offset: 2582},
						name: "MatchRegexp",
					},
					&ruleRefExpr{
						pos:  position{line: 50, col: 29, offset: 2596},
						name: "NotMatchRegexp",
					},
				},
			},
		},
		{
			name: "Regexp",
			pos:  position{line: 51, col: 1, offset: 2612},
			expr: &actionExpr{
				pos: position{line: 51, col: 11, offset: 2622},
				run: (*parser).callonRegexp1,
				expr: &seqExpr{
					pos: position{line: 51, col: 11, offset: 2622},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 51, col: 11, offset: 2622},
							val:        "/",
							ignoreCase: false,
							want:       "\"/\"",
						},
						&oneOrMoreExpr{
							pos: position{line: 51, col: 15, offset: 2626},
							expr: &charClassMatcher{
								pos:        position{line: 51, col: 15, offset: 2626},
								val:        "[^/]",
								chars:      []rune{'/'},
								ignoreCase: false,
								inverted:   true,
							},
						},
						&litMatcher{
							pos:        position{line: 51, col: 21, offset: 2632},
							val:        "/",
							ignoreCase: false,
							want:       "\"/\"",
						},
						&zeroOrMoreExpr{
							pos: position{line: 51, col: 25, offset: 2636},
							expr: &charClassMatcher{
								pos:        position{line: 51, col: 25, offset: 2636},
								val:        "[g|m|D|i|x|s|u|U|A|J]",
								chars:      []rune{'g', '|', 'm', '|', 'D', '|', 'i', '|', 'x', '|', 's', '|', 'u', '|', 'U', '|', 'A', '|', 'J'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "MatchRegexp",
			pos:  position{line: 52, col: 1, offset: 2690},
			expr: &actionExpr{
				pos: position{line: 52, col: 16, offset: 2705},
				run: (*parser).callonMatchRegexp1,
				expr: &seqExpr{
					pos: position{line: 52, col: 16, offset: 2705},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 52, col: 16, offset: 2705},
							label: "left",
							expr: &ruleRefExpr{
								pos:  position{line: 52, col: 22, offset: 2711},
								name: "Param",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 52, col: 29, offset: 2718},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 52, col: 31, offset: 2720},
							val:        "=~",
							ignoreCase: false,
							want:       "\"=~\"",
						},
						&ruleRefExpr{
							pos:  position{line: 52, col: 36, offset: 2725},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 52, col: 38, offset: 2727},
							label: "right",
							expr: &ruleRefExpr{
								pos:  position{line: 52, col: 45, offset: 2734},
								name: "Regexp",
							},
						},
					},
				},
			},
		},
		{
			name: "NotMatchRegexp",
			pos:  position{line: 53, col: 1, offset: 2783},
			expr: &actionExpr{
				pos: position{line: 53, col: 19, offset: 2801},
				run: (*parser).callonNotMatchRegexp1,
				expr: &seqExpr{
					pos: position{line: 53, col: 19, offset: 2801},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 53, col: 19, offset: 2801},
							label: "left",
							expr: &ruleRefExpr{
								pos:  position{line: 53, col: 25, offset: 2807},
								name: "Param",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 53, col: 32, offset: 2814},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 53, col: 34, offset: 2816},
							val:        "!~",
							ignoreCase: false,
							want:       "\"!~\"",
						},
						&ruleRefExpr{
							pos:  position{line: 53, col: 39, offset: 2821},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 53, col: 41, offset: 2823},
							label: "right",
							expr: &ruleRefExpr{
								pos:  position{line: 53, col: 48, offset: 2830},
								name: "Regexp",
							},
						},
					},
				},
			},
		},
		{
			name: "And",
			pos:  position{line: 56, col: 1, offset: 2892},
			expr: &actionExpr{
				pos: position{line: 56, col: 8, offset: 2899},
				run: (*parser).callonAnd1,
				expr: &seqExpr{
					pos: position{line: 56, col: 8, offset: 2899},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 56, col: 8, offset: 2899},
							label: "first",
							expr: &choiceExpr{
								pos: position{line: 56, col: 15, offset: 2906},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 56, col: 15, offset: 2906},
										name: "Bracket",
									},
									&ruleRefExpr{
										pos:  position{line: 56, col: 25, offset: 2916},
										name: "Statements",
									},
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 56, col: 37, offset: 2928},
							label: "rest",
							expr: &oneOrMoreExpr{
								pos: position{line: 56, col: 42, offset: 2933},
								expr: &seqExpr{
									pos: position{line: 56, col: 43, offset: 2934},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 56, col: 43, offset: 2934},
											name: "_",
										},
										&litMatcher{
											pos:        position{line: 56, col: 45, offset: 2936},
											val:        "&&",
											ignoreCase: false,
											want:       "\"&&\"",
										},
										&ruleRefExpr{
											pos:  position{line: 56, col: 50, offset: 2941},
											name: "_",
										},
										&choiceExpr{
											pos: position{line: 56, col: 53, offset: 2944},
											alternatives: []interface{}{
												&ruleRefExpr{
													pos:  position{line: 56, col: 53, offset: 2944},
													name: "Bracket",
												},
												&ruleRefExpr{
													pos:  position{line: 56, col: 63, offset: 2954},
													name: "Statements",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Or",
			pos:  position{line: 57, col: 1, offset: 3001},
			expr: &actionExpr{
				pos: position{line: 57, col: 7, offset: 3007},
				run: (*parser).callonOr1,
				expr: &seqExpr{
					pos: position{line: 57, col: 7, offset: 3007},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 57, col: 7, offset: 3007},
							label: "first",
							expr: &choiceExpr{
								pos: position{line: 57, col: 14, offset: 3014},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 57, col: 14, offset: 3014},
										name: "And",
									},
									&ruleRefExpr{
										pos:  position{line: 57, col: 20, offset: 3020},
										name: "Bracket",
									},
									&ruleRefExpr{
										pos:  position{line: 57, col: 30, offset: 3030},
										name: "Statements",
									},
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 57, col: 42, offset: 3042},
							label: "rest",
							expr: &oneOrMoreExpr{
								pos: position{line: 57, col: 47, offset: 3047},
								expr: &seqExpr{
									pos: position{line: 57, col: 48, offset: 3048},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 57, col: 48, offset: 3048},
											name: "_",
										},
										&litMatcher{
											pos:        position{line: 57, col: 50, offset: 3050},
											val:        "||",
											ignoreCase: false,
											want:       "\"||\"",
										},
										&ruleRefExpr{
											pos:  position{line: 57, col: 55, offset: 3055},
											name: "_",
										},
										&choiceExpr{
											pos: position{line: 57, col: 58, offset: 3058},
											alternatives: []interface{}{
												&ruleRefExpr{
													pos:  position{line: 57, col: 58, offset: 3058},
													name: "And",
												},
												&ruleRefExpr{
													pos:  position{line: 57, col: 64, offset: 3064},
													name: "Bracket",
												},
												&ruleRefExpr{
													pos:  position{line: 57, col: 74, offset: 3074},
													name: "Statements",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name:        "_",
			displayName: "\"whitespace\"",
			pos:         position{line: 59, col: 1, offset: 3121},
			expr: &zeroOrMoreExpr{
				pos: position{line: 59, col: 19, offset: 3139},
				expr: &charClassMatcher{
					pos:        position{line: 59, col: 19, offset: 3139},
					val:        "[ \\n\\t\\r]",
					chars:      []rune{' ', '\n', '\t', '\r'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 60, col: 1, offset: 3150},
			expr: &notExpr{
				pos: position{line: 60, col: 8, offset: 3157},
				expr: &anyMatcher{
					line: 60, col: 9, offset: 3158,
				},
			},
		},
	},
}

func (c *current) onInput1(expr interface{}) (interface{}, error) {
	return expr, nil
}

func (p *parser) callonInput1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInput1(stack["expr"])
}

func (c *current) onBracket1(expr interface{}) (interface{}, error) {
	return expr, nil
}

func (p *parser) callonBracket1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBracket1(stack["expr"])
}

func (c *current) onParam1() (interface{}, error) {
	return parseParam(c.text)
}

func (p *parser) callonParam1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onParam1()
}

func (c *current) onNull1() (interface{}, error) {
	return parseNull()
}

func (p *parser) callonNull1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNull1()
}

func (c *current) onBoolean1() (interface{}, error) {
	return parseBoolean(c.text)
}

func (p *parser) callonBoolean1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBoolean1()
}

func (c *current) onFloat1() (interface{}, error) {
	return parseFloat(c.text)
}

func (p *parser) callonFloat1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFloat1()
}

func (c *current) onInteger1() (interface{}, error) {
	return parseInteger(c.text)
}

func (p *parser) callonInteger1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInteger1()
}

func (c *current) onString1() (interface{}, error) {
	return parseString(c.text)
}

func (p *parser) callonString1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onString1()
}

func (c *current) onDateTime1(val interface{}) (interface{}, error) {
	return parseDateTime(val)
}

func (p *parser) callonDateTime1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDateTime1(stack["val"])
}

func (c *current) onEqual1(left, right interface{}) (interface{}, error) {
	return parseEquals(left, right)
}

func (p *parser) callonEqual1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEqual1(stack["left"], stack["right"])
}

func (c *current) onNotEqual1(left, right interface{}) (interface{}, error) {
	return parseNotEquals(left, right)
}

func (p *parser) callonNotEqual1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNotEqual1(stack["left"], stack["right"])
}

func (c *current) onLessThan1(left, right interface{}) (interface{}, error) {
	return parseLessThan(left, right)
}

func (p *parser) callonLessThan1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLessThan1(stack["left"], stack["right"])
}

func (c *current) onLessThanEqual1(left, right interface{}) (interface{}, error) {
	return parseLessThanEqual(left, right)
}

func (p *parser) callonLessThanEqual1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLessThanEqual1(stack["left"], stack["right"])
}

func (c *current) onGreaterThan1(left, right interface{}) (interface{}, error) {
	return parseGreaterThan(left, right)
}

func (p *parser) callonGreaterThan1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onGreaterThan1(stack["left"], stack["right"])
}

func (c *current) onGreaterThanEqual1(left, right interface{}) (interface{}, error) {
	return parseGreaterThanEqual(left, right)
}

func (p *parser) callonGreaterThanEqual1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onGreaterThanEqual1(stack["left"], stack["right"])
}

func (c *current) onBetween1(left, start, end interface{}) (interface{}, error) {
	return parseBetween(left, start, end)
}

func (p *parser) callonBetween1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBetween1(stack["left"], stack["start"], stack["end"])
}

func (c *current) onStartsWith1(left, right interface{}) (interface{}, error) {
	return parseStartsWith(left, right)
}

func (p *parser) callonStartsWith1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStartsWith1(stack["left"], stack["right"])
}

func (c *current) onEndsWith1(left, right interface{}) (interface{}, error) {
	return parseEndsWith(left, right)
}

func (p *parser) callonEndsWith1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEndsWith1(stack["left"], stack["right"])
}

func (c *current) onSlice1(elements interface{}) (interface{}, error) {
	return parseSlice(elements)
}

func (p *parser) callonSlice1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSlice1(stack["elements"])
}

func (c *current) onInSlice1(left, right interface{}) (interface{}, error) {
	return parseInSlice(left, right)
}

func (p *parser) callonInSlice1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInSlice1(stack["left"], stack["right"])
}

func (c *current) onNotInSlice1(left, right interface{}) (interface{}, error) {
	return parseNotInSlice(left, right)
}

func (p *parser) callonNotInSlice1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNotInSlice1(stack["left"], stack["right"])
}

func (c *current) onHas1(left, right interface{}) (interface{}, error) {
	return parseHas(left, right)
}

func (p *parser) callonHas1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onHas1(stack["left"], stack["right"])
}

func (c *current) onNotHas1(left, right interface{}) (interface{}, error) {
	return parseNotHas(left, right)
}

func (p *parser) callonNotHas1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNotHas1(stack["left"], stack["right"])
}

func (c *current) onHasAny1(left, right interface{}) (interface{}, error) {
	return parseHasAny(left, right)
}

func (p *parser) callonHasAny1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onHasAny1(stack["left"], stack["right"])
}

func (c *current) onHasAll1(left, right interface{}) (interface{}, error) {
	return parseHasAll(left, right)
}

func (p *parser) callonHasAll1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onHasAll1(stack["left"], stack["right"])
}

func (c *current) onRegexp1() (interface{}, error) {
	return parseRegexp(c.text)
}

func (p *parser) callonRegexp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRegexp1()
}

func (c *current) onMatchRegexp1(left, right interface{}) (interface{}, error) {
	return parseMatchRegexp(left, right)
}

func (p *parser) callonMatchRegexp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMatchRegexp1(stack["left"], stack["right"])
}

func (c *current) onNotMatchRegexp1(left, right interface{}) (interface{}, error) {
	return parseNotMatchRegexp(left, right)
}

func (p *parser) callonNotMatchRegexp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNotMatchRegexp1(stack["left"], stack["right"])
}

func (c *current) onAnd1(first, rest interface{}) (interface{}, error) {
	return parseAnd(first, rest)
}

func (p *parser) callonAnd1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAnd1(stack["first"], stack["rest"])
}

func (c *current) onOr1(first, rest interface{}) (interface{}, error) {
	return parseOr(first, rest)
}

func (p *parser) callonOr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOr1(stack["first"], stack["rest"])
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i interface{}, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]interface{}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type recoveryExpr struct {
	pos          position
	expr         interface{}
	recoverExpr  interface{}
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]interface{}
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr interface{}) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]interface{}, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() interface{}
}

var statePool = &sync.Pool{
	New: func() interface{} { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRule(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val interface{}
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExpr(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExpr(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]interface{}, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExpr(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
